# cluster commands
cluster: 
  # Make the hpc output folder for the rule
  mkdir -p log/hpc/`date +"%Y-%m-%d"`/{rule} &&
  sbatch 
    --job-name=smk-{rule}-{wildcards}
    --output log/hpc/`date +"%Y-%m-%d"`/{rule}/{rule}-{wildcards}-%j.out 
    --account=pschloss1
    --partition={resources.partition} 
    --time={resources.time_min} 
    --mem={resources.mem_mb} 
    --cpus-per-task={threads} 

# default resources used for rules with no Resources specified
default-resources: 
  - mem_mb=4000
  - partition=standard
  - time_min=360
  - threads=4
  
# snakemake args
jobs: 999
printshellcmds: True
scheduler: "greedy"
rerun-incomplete: true
use-conda: true
conda-frontend: "mamba"
keep-going: true
latency-wait: 120
# Max resources at a time for all jobs
#resources: [cpus=100, mem_mb=100000]
