__default__:
  - account_slurm: "YOUR_ACCOUNT",
  - partition: "standard",
  - jobname: "{rule}.{wildcards}",
  - nodes: 1,
  - procs: 1,
  - pmem: "4GB",
  - walltime: "24:00:00",
  - email: "YOUR_EMAIL",
  - mailon: "a",
  - mail_type: "FAIL",
  - jobout: "oe",
  - outdir: "log/hpc/jobs/",
  - outfile: "log/hpc/jobs/{rule}.{wildcards}.out"

process_data:
  - procs: "{resources.procs}"

calc_dists:
  - procs: "{resources.procs}"

cluster_OTUs:
  - procs: "{resources.procs}"